package ast;

import ast.nodes.WhileStatement;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;

/**
 * Represents a node in a syntax tree structure
 */
public abstract class Node {

    /**
     * The children of this ASTNode
     */
    protected ArrayList<Node> children = new ArrayList<>();

    /**
     * Accepts the visitor and calls the correct "visitNode" function on the visitor
     *
     * @param visitor the visitor to be called
     * @see Visitor
     */
    public abstract <T,S> T accept(Visitor<T,S> visitor, S data);


    /**
     * Gets a list of all child nodes for this Node
     *
     * @return the child list as an unmodifiable list
     */
    public final List<Node> getChildren(){
        return Collections.unmodifiableList(this.children);
    }


    public abstract Integer initialNode();

    public abstract Set<Integer> finalNodes();

    public abstract List<Edge> flow();

    public abstract List<Node> blocks();

    private int label;

    public void setLabel(int label)
    {
        this.label = label;
    }

    public int getLabel(){
        return this.label;
    }

    protected static List<Edge> flowForStatementList(List<Node> statements)
    {
        List<Edge> flow = new ArrayList<>();

        for (int s2Index = 1; s2Index < statements.size(); s2Index++){
            int s1Index = s2Index - 1;
            Node s1 = statements.get(s1Index);
            for (int l : s1.finalNodes())
            {
                Node s2 = statements.get(s2Index);

                // The edge from a final node of a while statement to the next can only follow the "false" branch
                // Since this edge is not generated by the while statement itself, the default is set to false here
                flow.add(new Edge(l, s2.initialNode(), false));
            }
        }

        for (int a = 0; a < statements.size(); a++) {
            flow.addAll(statements.get(a).flow());
        }

        return flow;
    }


    /**
	 * Adds the given node to the child list if it is not null.
	 * 
	 * @param node the node to add
	 */
	protected void addChildNode(Node node){
		if(node != null){
			this.children.add(node);
		}
	}
	
	/**
	 * Adds all the nodes in the given list to the child list
	 * 
	 * @param nodes the child nodes to add
	 */
	protected void addChildNodes(List<Node> nodes){
		this.children.addAll(nodes);
	}
}
